<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYwol5vz\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYwol5vz/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYwol5vz.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYwol5vz\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYwol5vz\appDevDebugProjectContainer([
    'container.build_hash' => 'Ywol5vz',
    'container.build_id' => '8c131d44',
    'container.build_time' => 1622226337,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYwol5vz');
