<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerElru50b\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerElru50b/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerElru50b.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerElru50b\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerElru50b\appProdProjectContainer([
    'container.build_hash' => 'Elru50b',
    'container.build_id' => '0bc7007f',
    'container.build_time' => 1622403948,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerElru50b');
